# this example shows how to connect an OpenTelemetry Collector with a Jaeger instance in OpenShift,
# which is provisioned using TLS automatically. We use the inject-cabundle in the config map to
# get access to the CA that signed the certs, and tell the operator to mount the config map into the
# provisioned deployments and daemonsets
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cabundle
  annotations:
    "service.beta.openshift.io/inject-cabundle": "true"
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetrycollector-sample
spec:
  volumeMounts:
  - name: cabundle-volume
    mountPath: /etc/pki/ca-trust/source/service-ca
    readOnly: true
  volumes:
  - name: cabundle-volume
    configMap:
      name: cabundle

  config: |
    receivers:
      jaeger:
        protocols:
          grpc: {}

    processors:
      batch: {}

    exporters:
      otlp:
        endpoint: "simplest-collector-headless.default.svc:14250"
        tls:
          ca_file: "/etc/pki/ca-trust/source/service-ca/service-ca.crt"
          server_name_override: "simplest-collector-headless.default.svc.cluster.local"

    service:
      pipelines:
        traces:
          receivers: [jaeger]
          processors: []
          exporters: [otlp]
