## Append samples you want in your CSV to this file as resources ##
resources:
- core_v1alpha1_opentelemetrycollector.yaml
- core_v1beta1_opentelemetrycollector.yaml
- instrumentation_v1alpha1_instrumentation.yaml
- _v1alpha1_opampbridge.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
