- op: add
  path: "/spec/template/spec/containers/0/args"
  value:
    - --zap-log-level=info
    - --zap-time-encoding=rfc3339nano
- op: add
  path: "/spec/template/spec/containers/0/env/-"
  value:
    name: METRICS_ADDR
    value: ":8443"
- op: add
  path: "/spec/template/spec/containers/0/env/-"
  value:
    name: METRICS_SECURE
    value: "true"
- op: add
  path: "/spec/template/spec/containers/0/env/-"
  value:
    name: METRICS_TLS_CERT_FILE
    value: "/var/run/tls/server/tls.crt"
- op: add
  path: "/spec/template/spec/containers/0/env/-"
  value:
    name: METRICS_TLS_KEY_FILE
    value: "/var/run/tls/server/tls.key"
- op: add
  path: "/spec/template/spec/containers/0/env/-"
  value:
    name: ENABLE_LEADER_ELECTION
    value: "true"
- op: add
  path: "/spec/template/spec/containers/0/env/-"
  value:
    name: ENABLE_NGINX_AUTO_INSTRUMENTATION
    value: "true"
- op: add
  path: "/spec/template/spec/containers/0/env/-"
  value:
    name: ENABLE_GO_AUTO_INSTRUMENTATION
    value: "true"
- op: add
  path: "/spec/template/spec/containers/0/env/-"
  value:
    name: OPENSHIFT_CREATE_DASHBOARD
    value: "true"
- op: add
  path: "/spec/template/spec/containers/0/env/-"
  value:
    name: ENABLE_CR_METRICS
    value: "true"
- op: add
  path: "/spec/template/spec/containers/0/env/-"
  value:
    name: CREATE_SM_OPERATOR_METRICS
    value: "true"
- op: add
  path: "/spec/template/spec/containers/0/env/-"
  value:
    name: FEATURE_GATES
    value: "operator.networkpolicy,operand.networkpolicy"
