# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/opentelemetry.io_opentelemetrycollectors.yaml
- bases/opentelemetry.io_opentelemetrycollectordistributions.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# patches here are for enabling the conversion webhook for each CRD
- patches/webhook_in_opentelemetrycollectors.yaml
- patches/webhook_in_opentelemetrycollectordistributions.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# patches here are for enabling the CA injection for each CRD
- patches/cainjection_in_opentelemetrycollectors.yaml
- patches/cainjection_in_opentelemetrycollectordistributions.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
