name: "Prepare the release"
on:
  push:
    tags:
    - 'v*'

jobs:
  unit-tests:
    runs-on: ubuntu-20.04
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - uses: actions/checkout@v2.3.4

    - name: "install kubebuilder"
      run: ./hack/install-kubebuilder.sh

    - uses: jpkrohling/setup-operator-sdk@v1.1.0
      with:
        operator-sdk-version: v1.6.1

    - name: "generate release resources"
      run: make release-artifacts IMG_PREFIX="quay.io/opentelemetry"

    - name: "create the release in GitHub"
      env:
        GH_WRITE_TOKEN: ${{ secrets.GH_WRITE_TOKEN }}
      run: ./.ci/create-release-github.sh
