name: "Scorecard tests"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  scorecard-tests:
    name: test on k8s
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kube-version:
          - "1.25"
          - "1.35"

    steps:

      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        id: setup-go
        with:
          go-version: "~1.25.7"

      - name: Check out code into the Go module directory
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Cache tools
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: bin
          key: tools-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('Makefile') }}-${{ steps.setup-go.outputs.go-version }}

      - name: Install tools
        run: make install-tools

      - name: "start kind"
        env:
          KUBE_VERSION: ${{ matrix.kube-version }}
        run: make start-kind

      - name: "wait until cluster is ready"
        run:  kubectl wait --timeout=5m --for=condition=available deployment/coredns -n kube-system

      - name: "run scorecard test"
        run: make scorecard-tests

  scorecard-tests-check:
    runs-on: ubuntu-latest
    if: always()
    needs: [scorecard-tests]
    steps:
      - name: Print result
        run: echo ${{ needs.scorecard-tests.result }}
      - name: Interpret result
        run: |
          if [[ success == ${{ needs.scorecard-tests.result }} ]]
          then
            echo "All matrix jobs passed!"
          else
            echo "One or more matrix jobs failed."
            false
          fi
