name: shellcheck
on:
  push:
    branches:
      - main
  pull_request:
permissions: {}

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-24.04
    env:
      # renovate: datasource=github-releases depName=https://github.com/koalaman/shellcheck
      SHELLCHECK_VERSION: v0.10.0
    steps:
      - uses: actions/checkout@v4
      - name: shellcheck ci scripts
        uses: ludeeus/action-shellcheck@2.0.0
        env:
          SHELLCHECK_OPTS: -x -e SC2059 -e SC2086
        with:
          scandir: ".ci"
          severity: warning
          version: ${{ env.SHELLCHECK_VERSION }}
      - name: shellcheck hack scripts
        uses: ludeeus/action-shellcheck@2.0.0
        env:
          SHELLCHECK_OPTS: -x -e SC2059 -e SC2086
        with:
          scandir: "hack"
          severity: warning
          version: ${{ env.SHELLCHECK_VERSION }}